apiVersion: apps/v1
kind: Deployment
metadata: 
  name: client-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  # template for each pod
  template:
    metadata:
      labels:
        component: web
    spec:
      # each pod can have different containers doing 1 job
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            # nginx inside the multi-client will listen on this
            - containerPort: 3000