apiVersion: networking.k8s.io/v1
# UPDATE API
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # ADD ANNOTATION - if we end up matching a route, remove the "/api" part
    # so we don't have to keep adding "api" in our server route
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          # 1. CLIENT PATH
          - path: /?(.*)
            # if the route comes here:
            pathType: Prefix
            backend:
              service:
                # send to pods governed by server-cluserIP service
                name: client-cluster-ip-service
                port:
                  number: 3000
           # 2. SERVER PATH
           # if the route comes here:
          - path: /api/?(.*)
            pathType: Prefix
            # send to pods governed by server-cluserIP service
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000
