apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    # to attach to postgres
    component: postgres
  ports:
    # how other pods access to our pod. come in using this port
    - port: 5432
      # port on the target port (postgres) that we provide access to
      targetPort: 5432
