apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  # template for each pod
  template:
    metadata:
      labels:
        component: redis
    spec:
      # each pod can have different containers doing 1 job
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379