apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  # template for each pod
  template:
    metadata:
      labels:
        component: worker
    spec:
      # each pod can have different containers doing 1 job
      containers:
        - name: worker
          image: freecode23/fibonacci-worker-k8s
          # no ports
          env:
            # redis env
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            